name: Merge any release branch to develop
on:
  push:
    branches:
    - "release/*"  # Support wildcard matching
    - "hotfix/*"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""                                 # If blank, default: triggered branch
        destination_branch: "develop"                      # If blank, default: master
        pr_title: "Bot: Merge ${{ github.ref }} into master" # Title of pull request
        pr_body: ":crown: *Automated PR* ${{github.actor}}"              # Full markdown support, requires pr_title to be set
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        github_token: ${{ secrets.GITHUB_TOKEN }}
