name: Merge master to release
on:
  push:
    branches:
      - 'master'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge release -> develop
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          target_branch: 'release/*'
          github_token: ${{ secrets.GITHUB_TOKEN }}
